# Generated by Django 4.1.5 on 2023-02-11 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_alter_medication_notes_alter_medication_refill_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medication',
            name='notes',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='medication',
            name='refill_date',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
    ]
