# Generated by Django 4.1.5 on 2023-02-12 02:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_alter_medication_notes_alter_medication_refill_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medication',
            name='refill_date',
            field=models.CharField(max_length=25, null=True),
        ),
    ]
