# Generated by Django 4.1.5 on 2023-01-31 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_event_all_day_alter_event_end_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='author',
            field=models.CharField(default='Anna', max_length=20),
            preserve_default=False,
        ),
    ]
