# Generated by Django 4.1.5 on 2023-02-04 00:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_note_author'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='end_time',
            new_name='end',
        ),
        migrations.RenameField(
            model_name='event',
            old_name='start_time',
            new_name='start',
        ),
        migrations.RemoveField(
            model_name='event',
            name='date',
        ),
    ]
